# Generated by Django 5.0.1 on 2024-02-04 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0002_problem_public_date_alter_problem_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='input_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='output_format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sameple_intput',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.TextField(null=True),
        ),
    ]
