# Generated by Django 5.0.1 on 2024-02-04 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0004_rename_sameple_intput_problem_sample_intput'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='sample_intput',
            new_name='sample_input',
        ),
    ]
