# Generated by Django 5.0.1 on 2024-02-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problemset', '0005_rename_sample_intput_problem_sample_input'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='expected_output',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_data',
            field=models.TextField(null=True),
        ),
    ]
